# Site settings
title: DODECAEDRO.MX
description: > # this means to ignore newlines until "baseurl:"
  Dodecaedro es una página comprometida con la cultura del cine, literatura, artes plásticas, y música local mexicana.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dodecaedro.mx" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/